//@version=6
indicator("Daddy's Special Mix", shorttitle="DSM", overlay=true, dynamic_requests=true)

// ----------
//  Moving Averages
// ----------

group1 = "Moving Averages"

ma_base_length = input.int(50, title="Base Length", group=group1)
ma_base_type = input.string("EMA", title="Base Type", options=["SMA", "EMA"], group=group1)

ma_pb_length = input.int(9, title="Pullback Length", group=group1)

ma_long_length = input.int(200, title="Long-term Length", group=group1)

// Moving average calculation function
calculate_ma(ma_type, length) =>
    ma_type == "SMA" ? ta.sma(close, length) : ta.ema(close, length)

// Calculate the moving averages
ma_base = calculate_ma(ma_base_type, ma_base_length)
ma_pb = calculate_ma("EMA", ma_pb_length)
ma_long = calculate_ma("SMA", ma_long_length)

// Plot moving averages
plot(ma_base, color=color.yellow, linewidth=2, title="MA Base")
plot(ma_pb, color=color.aqua, linewidth=1, title="MA Pullback")
plot(ma_long, color=color.white, linewidth=2, title="MA Long-term")

group2 = "Average True Range"
atr_length = input.int(20, "Length", group=group2)
atr_buffer = input.float(0.1, "Buffer multiplier", group=group2)
atr_body = input.float(0.5, "Body multiplier", group=group2)

group5 = "Entry Settings"
clearing_bars = input.int(3, "Bars to clear", group=group5)
min_body_perc = input.float(50, "Min entry candle body %", minval=20, maxval=95, group=group5)
max_entries = input.int(2, "Maximum entries", group=group5)
rsi_period = input.int(14, "RSI Period", minval=5, group=group5)


// ----------
// Global Variables
// ----------

bool is_bear = close < open
bool is_bull = close > open
float atr = ta.atr(atr_length)
float rsi = ta.rsi(close, rsi_period)
int entry = na
int exit = na
var bool entry_taken = false
var float pullback = na
var int trend = 0


// ----------
// RESET
// ----------

bool cross_bear = ta.crossunder(close, ma_base)
bool cross_bull = ta.crossover(close, ma_base)

if cross_bear or cross_bull
    entry_taken := false
    pullback := na
    trend := cross_bull ? 1 : 2

// ----------
// ENTRY
// ----------

float entry_highest = ta.highest(high, clearing_bars)[1]
float entry_lowest = ta.lowest(low, clearing_bars)[1]

if not entry_taken
    float candle_body_size = math.abs(close - open)
    float candle_full_size = math.abs(high - low)
    float prev_full_size = math.abs(high[1] - low[1])

    float body_percent = candle_body_size / candle_full_size
    bool body_ok = body_percent >= min_body_perc / 100 and candle_full_size >= atr * atr_body and candle_full_size < atr * 4

    float buffer = atr * atr_buffer
    bool bear_trend = trend == 2 and is_bear and close < entry_lowest - buffer and close < low[1] and close < ma_pb and rsi < 50 and (na(pullback) or close < pullback)
    bool bull_trend = trend == 1 and is_bull and close > entry_highest + buffer and close > high[1] and close > ma_pb and rsi > 50 and (na(pullback) or close > pullback)
    bool trend_ok = bear_trend or bull_trend

    bool engulfing = body_ok and candle_body_size > prev_full_size and ((bull_trend and is_bear[1]) or (bear_trend and is_bull[1]))

    if engulfing
        entry := trend

    if na(pullback)
        bool short_cross = low < ma_pb and high > ma_pb
        if trend == 1 and (is_bear or short_cross) and open > ma_base and low > ma_base
            pullback := high

        else if trend == 2 and (is_bull or short_cross) and open < ma_base and high < ma_base
            pullback := low

    // Entry validations
    else if body_ok and bull_trend
        entry := 1

    else if body_ok and bear_trend
        entry := 2

    if not na(entry)
        entry_taken := true


// ----------
//  VISUAL
// ----------

entry_color = color.white
plot_size = size.tiny
plot_bull = location.belowbar
plot_bear = location.abovebar

plotshape(entry == 1, title="Long Entry", style=shape.triangleup, location=plot_bull, color=entry_color, size=plot_size)
plotshape(entry == 2, title="Short Entry", style=shape.triangledown, location=plot_bear, color=entry_color, size=plot_size)


// ----------
//  ALERTS
// ----------

bool alert_check = not na(entry)
alertcondition(alert_check, title="New entry", message="New signal detected. Confirm the direction of the next candle before entering. Happy trading!")

// ----------
//  DAILY LEVELS
// ----------

bool is_ltf = timeframe.in_seconds() <= 43200

[pdh, pdl, today_open, day_start] = request.security(syminfo.tickerid, "D", [high, low, open, time], lookahead=barmerge.lookahead_off)
pmi = (pdh + pdl) / 2

bool new_day = ta.change(day_start) != 0 and is_ltf
int future_bar = time + 5 * (time - time[1])


// ----------
//  DAILY LEVEL LINES
// ----------

var label middle_label = na
var label open_label = na
var label pdh_label = na
var label pdl_label = na
var line middle_line = na
var line open_line = na
var line pdh_line = na
var line pdl_line = na

if new_day

    prev_down = pdl[1]
    prev_up = pdh[1]
    prev_middle = (prev_up + prev_down) / 2

    label.delete(middle_label)
    label.delete(open_label)
    label.delete(pdh_label)
    label.delete(pdl_label)
    line.delete(middle_line)
    line.delete(open_line)
    line.delete(pdh_line)
    line.delete(pdl_line)

    line_style = line.style_dashed

    pdh_line := line.new(day_start, prev_up, future_bar, prev_up,
        xloc = xloc.bar_time,
        color = color.red,
        style = line_style)

    pdl_line := line.new(day_start, prev_down, future_bar, prev_down,
        xloc = xloc.bar_time,
        color = color.green,
        style = line_style)

    open_line := line.new(day_start, today_open, future_bar, today_open,
        xloc = xloc.bar_time,
        color = color.new(color.white, 20),
        style = line_style)

    middle_line := line.new(day_start, prev_middle, future_bar, prev_middle,
        xloc = xloc.bar_time,
        color = color.gray,
        style = line_style)

    pdh_label := label.new(future_bar, prev_up, "PDH",
        xloc = xloc.bar_time,
        style = label.style_label_left,
        textcolor = color.red,
        color = color.new(color.red, 100))

    pdl_label := label.new(future_bar, prev_down, "PDL",
        xloc = xloc.bar_time,
        style = label.style_label_left,
        textcolor = color.green,
        color = color.new(color.green, 100))

    open_label := label.new(future_bar, today_open, "OPEN",
        xloc = xloc.bar_time,
        style = label.style_label_left,
        textcolor = color.new(color.white, 20),
        color = color.new(color.white, 100))

    middle_label := label.new(future_bar, prev_middle, "MID",
        xloc = xloc.bar_time,
        style = label.style_label_left,
        textcolor = color.gray,
        color = color.new(color.gray, 100))